---
- name: download iso to /tmp
  get_url:
    url: https://releases.ubuntu.com/focal/ubuntu-20.04.6-live-server-amd64.iso
    checksum: sha256:b8f31413336b9393ad5d8ef0282717b2ab19f007df2e9ed5196c13d8f9153c8b
    dest: /tmp/

- name: install 7z
  apt:
    name: p7zip-full
    state: present

- name: extract to nfs export
  shell: 7z x /tmp/ubuntu-20.04.6-live-server-amd64.iso -o/exports/focal/
  args:
    creates: /exports/focal/

- name: create focal and autoinstall dirs
  file:
    path: /var/www/focal/autoinstall
    state: directory

- name: copy kernel and initrd
  copy:
    src: "/exports/focal/casper/{{item}}"
    dest: /var/www/focal/
    remote_src: yes
  loop:
    - vmlinuz
    - initrd

- name: copy cloud-config file
  copy:
    src: '{{ item }}'
    dest: /var/www/focal/autoinstall/
  loop:
    - user-data
    - meta-data

- name: chown dir
  file:
    path: /var/www/focal/
    owner: www-data
    recurse: yes

- name: create boot entry
  copy:
    src: script.ipxe
    dest: /var/www/

- name: fix nfs perms
  # workaround to https://bugs.launchpad.net/subiquity/+bug/1905296
  file:
    path: /exports/focal
    mode: a+rx
    recurse: yes
